// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package tokens

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type OauthClient struct {
	ID               pgtype.UUID        `json:"id"`
	ClientID         string             `json:"client_id"`
	ClientSecretHash pgtype.Text        `json:"client_secret_hash"`
	Name             string             `json:"name"`
	RedirectUris     []string           `json:"redirect_uris"`
	GrantTypes       []string           `json:"grant_types"`
	Scopes           []string           `json:"scopes"`
	IsConfidential   bool               `json:"is_confidential"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type RefreshToken struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	ClientID  string             `json:"client_id"`
	DeviceID  pgtype.UUID        `json:"device_id"`
	TokenHash string             `json:"token_hash"`
	Scope     string             `json:"scope"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	Revoked   bool               `json:"revoked"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID            pgtype.UUID        `json:"id"`
	Email         string             `json:"email"`
	PasswordHash  string             `json:"password_hash"`
	EmailVerified bool               `json:"email_verified"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type UserDevice struct {
	ID         pgtype.UUID        `json:"id"`
	UserID     pgtype.UUID        `json:"user_id"`
	ClientID   string             `json:"client_id"`
	DeviceName pgtype.Text        `json:"device_name"`
	UserAgent  string             `json:"user_agent"`
	IpAddress  string             `json:"ip_address"`
	LastUsedAt pgtype.Timestamptz `json:"last_used_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	Revoked    bool               `json:"revoked"`
}
