// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: queries.sql

package tokens

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRefreshToken = `-- name: CreateRefreshToken :exec
INSERT INTO refresh_tokens (id, user_id, client_id, device_id, token_hash, scope, expires_at, revoked, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type CreateRefreshTokenParams struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	ClientID  string             `json:"client_id"`
	DeviceID  pgtype.UUID        `json:"device_id"`
	TokenHash string             `json:"token_hash"`
	Scope     string             `json:"scope"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	Revoked   bool               `json:"revoked"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) error {
	_, err := q.db.Exec(ctx, createRefreshToken,
		arg.ID,
		arg.UserID,
		arg.ClientID,
		arg.DeviceID,
		arg.TokenHash,
		arg.Scope,
		arg.ExpiresAt,
		arg.Revoked,
		arg.CreatedAt,
	)
	return err
}

const deleteExpiredRefreshTokens = `-- name: DeleteExpiredRefreshTokens :execrows
DELETE FROM refresh_tokens WHERE expires_at < $1
`

func (q *Queries) DeleteExpiredRefreshTokens(ctx context.Context, expiresAt pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredRefreshTokens, expiresAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getActiveFCMTokensByUserID = `-- name: GetActiveFCMTokensByUserID :many
SELECT DISTINCT fcm_token FROM refresh_tokens
WHERE user_id = $1 AND fcm_token IS NOT NULL AND revoked = FALSE AND expires_at > $2
`

type GetActiveFCMTokensByUserIDParams struct {
	UserID    pgtype.UUID        `json:"user_id"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) GetActiveFCMTokensByUserID(ctx context.Context, arg GetActiveFCMTokensByUserIDParams) ([]pgtype.Text, error) {
	rows, err := q.db.Query(ctx, getActiveFCMTokensByUserID, arg.UserID, arg.ExpiresAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.Text
	for rows.Next() {
		var fcm_token pgtype.Text
		if err := rows.Scan(&fcm_token); err != nil {
			return nil, err
		}
		items = append(items, fcm_token)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getActiveRefreshTokensByUserAndDevice = `-- name: GetActiveRefreshTokensByUserAndDevice :many
SELECT id, user_id, client_id, device_id, token_hash, scope, expires_at, revoked, created_at, fcm_token FROM refresh_tokens
WHERE user_id = $1 AND device_id = $2 AND revoked = FALSE AND expires_at > $3
ORDER BY created_at DESC
`

type GetActiveRefreshTokensByUserAndDeviceParams struct {
	UserID    pgtype.UUID        `json:"user_id"`
	DeviceID  pgtype.UUID        `json:"device_id"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) GetActiveRefreshTokensByUserAndDevice(ctx context.Context, arg GetActiveRefreshTokensByUserAndDeviceParams) ([]RefreshToken, error) {
	rows, err := q.db.Query(ctx, getActiveRefreshTokensByUserAndDevice, arg.UserID, arg.DeviceID, arg.ExpiresAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RefreshToken
	for rows.Next() {
		var i RefreshToken
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ClientID,
			&i.DeviceID,
			&i.TokenHash,
			&i.Scope,
			&i.ExpiresAt,
			&i.Revoked,
			&i.CreatedAt,
			&i.FcmToken,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRefreshTokenByHash = `-- name: GetRefreshTokenByHash :one
SELECT id, user_id, client_id, device_id, token_hash, scope, expires_at, revoked, created_at, fcm_token FROM refresh_tokens WHERE token_hash = $1
`

func (q *Queries) GetRefreshTokenByHash(ctx context.Context, tokenHash string) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, getRefreshTokenByHash, tokenHash)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ClientID,
		&i.DeviceID,
		&i.TokenHash,
		&i.Scope,
		&i.ExpiresAt,
		&i.Revoked,
		&i.CreatedAt,
		&i.FcmToken,
	)
	return i, err
}

const getRefreshTokenByID = `-- name: GetRefreshTokenByID :one
SELECT id, user_id, client_id, device_id, token_hash, scope, expires_at, revoked, created_at, fcm_token FROM refresh_tokens WHERE id = $1
`

func (q *Queries) GetRefreshTokenByID(ctx context.Context, id pgtype.UUID) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, getRefreshTokenByID, id)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ClientID,
		&i.DeviceID,
		&i.TokenHash,
		&i.Scope,
		&i.ExpiresAt,
		&i.Revoked,
		&i.CreatedAt,
		&i.FcmToken,
	)
	return i, err
}

const getRefreshTokensByDeviceID = `-- name: GetRefreshTokensByDeviceID :many
SELECT id, user_id, client_id, device_id, token_hash, scope, expires_at, revoked, created_at, fcm_token FROM refresh_tokens WHERE device_id = $1 ORDER BY created_at DESC
`

func (q *Queries) GetRefreshTokensByDeviceID(ctx context.Context, deviceID pgtype.UUID) ([]RefreshToken, error) {
	rows, err := q.db.Query(ctx, getRefreshTokensByDeviceID, deviceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RefreshToken
	for rows.Next() {
		var i RefreshToken
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ClientID,
			&i.DeviceID,
			&i.TokenHash,
			&i.Scope,
			&i.ExpiresAt,
			&i.Revoked,
			&i.CreatedAt,
			&i.FcmToken,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRefreshTokensByUserID = `-- name: GetRefreshTokensByUserID :many
SELECT id, user_id, client_id, device_id, token_hash, scope, expires_at, revoked, created_at, fcm_token FROM refresh_tokens WHERE user_id = $1 ORDER BY created_at DESC
`

func (q *Queries) GetRefreshTokensByUserID(ctx context.Context, userID pgtype.UUID) ([]RefreshToken, error) {
	rows, err := q.db.Query(ctx, getRefreshTokensByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RefreshToken
	for rows.Next() {
		var i RefreshToken
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ClientID,
			&i.DeviceID,
			&i.TokenHash,
			&i.Scope,
			&i.ExpiresAt,
			&i.Revoked,
			&i.CreatedAt,
			&i.FcmToken,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeRefreshToken = `-- name: RevokeRefreshToken :exec
UPDATE refresh_tokens SET revoked = TRUE WHERE id = $1
`

func (q *Queries) RevokeRefreshToken(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, revokeRefreshToken, id)
	return err
}

const revokeRefreshTokensByDeviceID = `-- name: RevokeRefreshTokensByDeviceID :exec
UPDATE refresh_tokens SET revoked = TRUE WHERE device_id = $1
`

func (q *Queries) RevokeRefreshTokensByDeviceID(ctx context.Context, deviceID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, revokeRefreshTokensByDeviceID, deviceID)
	return err
}

const revokeRefreshTokensByUserID = `-- name: RevokeRefreshTokensByUserID :exec
UPDATE refresh_tokens SET revoked = TRUE WHERE user_id = $1
`

func (q *Queries) RevokeRefreshTokensByUserID(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, revokeRefreshTokensByUserID, userID)
	return err
}

const revokeRefreshTokensExceptDevice = `-- name: RevokeRefreshTokensExceptDevice :exec
UPDATE refresh_tokens SET revoked = TRUE WHERE user_id = $1 AND device_id != $2
`

type RevokeRefreshTokensExceptDeviceParams struct {
	UserID   pgtype.UUID `json:"user_id"`
	DeviceID pgtype.UUID `json:"device_id"`
}

func (q *Queries) RevokeRefreshTokensExceptDevice(ctx context.Context, arg RevokeRefreshTokensExceptDeviceParams) error {
	_, err := q.db.Exec(ctx, revokeRefreshTokensExceptDevice, arg.UserID, arg.DeviceID)
	return err
}

const updateFCMToken = `-- name: UpdateFCMToken :exec
UPDATE refresh_tokens SET fcm_token = $2 WHERE token_hash = $1 AND revoked = FALSE
`

type UpdateFCMTokenParams struct {
	TokenHash string      `json:"token_hash"`
	FcmToken  pgtype.Text `json:"fcm_token"`
}

func (q *Queries) UpdateFCMToken(ctx context.Context, arg UpdateFCMTokenParams) error {
	_, err := q.db.Exec(ctx, updateFCMToken, arg.TokenHash, arg.FcmToken)
	return err
}
