// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package devices

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CountActiveUserDevicesByUserID(ctx context.Context, userID pgtype.UUID) (int64, error)
	CreateUserDevice(ctx context.Context, arg CreateUserDeviceParams) error
	DeleteUserDevice(ctx context.Context, id pgtype.UUID) error
	GetActiveUserDevicesByUserID(ctx context.Context, userID pgtype.UUID) ([]UserDevice, error)
	GetUserDeviceByID(ctx context.Context, id pgtype.UUID) (UserDevice, error)
	GetUserDevicesByUserAndClient(ctx context.Context, arg GetUserDevicesByUserAndClientParams) ([]UserDevice, error)
	GetUserDevicesByUserID(ctx context.Context, userID pgtype.UUID) ([]UserDevice, error)
	RevokeUserDevice(ctx context.Context, id pgtype.UUID) error
	RevokeUserDevicesByUserID(ctx context.Context, userID pgtype.UUID) error
	RevokeUserDevicesExceptOne(ctx context.Context, arg RevokeUserDevicesExceptOneParams) error
	UpdateUserDevice(ctx context.Context, arg UpdateUserDeviceParams) error
}

var _ Querier = (*Queries)(nil)
