// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package identities

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateUserIdentity(ctx context.Context, arg CreateUserIdentityParams) error
	DeleteUserIdentitiesByUserID(ctx context.Context, userID pgtype.UUID) error
	DeleteUserIdentity(ctx context.Context, id pgtype.UUID) error
	GetUserIdentitiesByUserID(ctx context.Context, userID pgtype.UUID) ([]UserIdentity, error)
	GetUserIdentityByProvider(ctx context.Context, arg GetUserIdentityByProviderParams) (UserIdentity, error)
}

var _ Querier = (*Queries)(nil)
