// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: queries.sql

package identities

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUserIdentity = `-- name: CreateUserIdentity :exec
INSERT INTO user_identities (id, user_id, provider, provider_user_id, created_at)
VALUES ($1, $2, $3, $4, $5)
`

type CreateUserIdentityParams struct {
	ID             pgtype.UUID        `json:"id"`
	UserID         pgtype.UUID        `json:"user_id"`
	Provider       string             `json:"provider"`
	ProviderUserID string             `json:"provider_user_id"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateUserIdentity(ctx context.Context, arg CreateUserIdentityParams) error {
	_, err := q.db.Exec(ctx, createUserIdentity,
		arg.ID,
		arg.UserID,
		arg.Provider,
		arg.ProviderUserID,
		arg.CreatedAt,
	)
	return err
}

const deleteUserIdentitiesByUserID = `-- name: DeleteUserIdentitiesByUserID :exec
DELETE FROM user_identities WHERE user_id = $1
`

func (q *Queries) DeleteUserIdentitiesByUserID(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteUserIdentitiesByUserID, userID)
	return err
}

const deleteUserIdentity = `-- name: DeleteUserIdentity :exec
DELETE FROM user_identities WHERE id = $1
`

func (q *Queries) DeleteUserIdentity(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteUserIdentity, id)
	return err
}

const getUserIdentitiesByUserID = `-- name: GetUserIdentitiesByUserID :many
SELECT id, user_id, provider, provider_user_id, created_at FROM user_identities WHERE user_id = $1
`

func (q *Queries) GetUserIdentitiesByUserID(ctx context.Context, userID pgtype.UUID) ([]UserIdentity, error) {
	rows, err := q.db.Query(ctx, getUserIdentitiesByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserIdentity
	for rows.Next() {
		var i UserIdentity
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Provider,
			&i.ProviderUserID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserIdentityByProvider = `-- name: GetUserIdentityByProvider :one
SELECT id, user_id, provider, provider_user_id, created_at FROM user_identities WHERE provider = $1 AND provider_user_id = $2
`

type GetUserIdentityByProviderParams struct {
	Provider       string `json:"provider"`
	ProviderUserID string `json:"provider_user_id"`
}

func (q *Queries) GetUserIdentityByProvider(ctx context.Context, arg GetUserIdentityByProviderParams) (UserIdentity, error) {
	row := q.db.QueryRow(ctx, getUserIdentityByProvider, arg.Provider, arg.ProviderUserID)
	var i UserIdentity
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ProviderUserID,
		&i.CreatedAt,
	)
	return i, err
}
