// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sessions

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type UserSession struct {
	ID               pgtype.UUID        `json:"id"`
	UserID           int64              `json:"user_id"`
	RefreshTokenHash string             `json:"refresh_token_hash"`
	DeviceID         pgtype.UUID        `json:"device_id"`
	FcmToken         pgtype.Text        `json:"fcm_token"`
	IpAddress        string             `json:"ip_address"`
	SessionInfo      []byte             `json:"session_info"`
	ClientID         string             `json:"client_id"`
	Scope            string             `json:"scope"`
	ExpiresAt        pgtype.Timestamptz `json:"expires_at"`
	Revoked          bool               `json:"revoked"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	LastUsedAt       pgtype.Timestamptz `json:"last_used_at"`
}
