// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: queries.sql

package sessions

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countActiveSessionsByUserID = `-- name: CountActiveSessionsByUserID :one
SELECT COUNT(*) FROM user_sessions
WHERE user_id = $1 AND revoked = FALSE AND expires_at > NOW()
`

func (q *Queries) CountActiveSessionsByUserID(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveSessionsByUserID, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSession = `-- name: CreateSession :exec
INSERT INTO user_sessions (
    id, user_id, refresh_token_hash, device_id, fcm_token,
    ip_address, session_info, client_id, scope, expires_at,
    revoked, created_at, last_used_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13
)
`

type CreateSessionParams struct {
	ID               pgtype.UUID        `json:"id"`
	UserID           int64              `json:"user_id"`
	RefreshTokenHash string             `json:"refresh_token_hash"`
	DeviceID         pgtype.UUID        `json:"device_id"`
	FcmToken         pgtype.Text        `json:"fcm_token"`
	IpAddress        string             `json:"ip_address"`
	SessionInfo      []byte             `json:"session_info"`
	ClientID         string             `json:"client_id"`
	Scope            string             `json:"scope"`
	ExpiresAt        pgtype.Timestamptz `json:"expires_at"`
	Revoked          bool               `json:"revoked"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	LastUsedAt       pgtype.Timestamptz `json:"last_used_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.Exec(ctx, createSession,
		arg.ID,
		arg.UserID,
		arg.RefreshTokenHash,
		arg.DeviceID,
		arg.FcmToken,
		arg.IpAddress,
		arg.SessionInfo,
		arg.ClientID,
		arg.Scope,
		arg.ExpiresAt,
		arg.Revoked,
		arg.CreatedAt,
		arg.LastUsedAt,
	)
	return err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :execrows
DELETE FROM user_sessions
WHERE expires_at < NOW() OR revoked = TRUE
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredSessions)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM user_sessions WHERE id = $1
`

func (q *Queries) DeleteSession(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteSession, id)
	return err
}

const getActiveFCMTokensByUserID = `-- name: GetActiveFCMTokensByUserID :many
SELECT fcm_token FROM user_sessions
WHERE user_id = $1 AND revoked = FALSE AND expires_at > NOW() AND fcm_token IS NOT NULL
`

func (q *Queries) GetActiveFCMTokensByUserID(ctx context.Context, userID int64) ([]pgtype.Text, error) {
	rows, err := q.db.Query(ctx, getActiveFCMTokensByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.Text
	for rows.Next() {
		var fcm_token pgtype.Text
		if err := rows.Scan(&fcm_token); err != nil {
			return nil, err
		}
		items = append(items, fcm_token)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getActiveSessionsByUserID = `-- name: GetActiveSessionsByUserID :many
SELECT id, user_id, refresh_token_hash, device_id, fcm_token, ip_address, session_info, client_id, scope, expires_at, revoked, created_at, last_used_at FROM user_sessions
WHERE user_id = $1 AND revoked = FALSE AND expires_at > NOW()
ORDER BY last_used_at DESC
`

func (q *Queries) GetActiveSessionsByUserID(ctx context.Context, userID int64) ([]UserSession, error) {
	rows, err := q.db.Query(ctx, getActiveSessionsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserSession
	for rows.Next() {
		var i UserSession
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.RefreshTokenHash,
			&i.DeviceID,
			&i.FcmToken,
			&i.IpAddress,
			&i.SessionInfo,
			&i.ClientID,
			&i.Scope,
			&i.ExpiresAt,
			&i.Revoked,
			&i.CreatedAt,
			&i.LastUsedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOldestActiveSessionByUserID = `-- name: GetOldestActiveSessionByUserID :one
SELECT id, user_id, refresh_token_hash, device_id, fcm_token, ip_address, session_info, client_id, scope, expires_at, revoked, created_at, last_used_at FROM user_sessions
WHERE user_id = $1 AND revoked = FALSE
ORDER BY created_at ASC
LIMIT 1
`

func (q *Queries) GetOldestActiveSessionByUserID(ctx context.Context, userID int64) (UserSession, error) {
	row := q.db.QueryRow(ctx, getOldestActiveSessionByUserID, userID)
	var i UserSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RefreshTokenHash,
		&i.DeviceID,
		&i.FcmToken,
		&i.IpAddress,
		&i.SessionInfo,
		&i.ClientID,
		&i.Scope,
		&i.ExpiresAt,
		&i.Revoked,
		&i.CreatedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const getSessionByDeviceID = `-- name: GetSessionByDeviceID :one
SELECT id, user_id, refresh_token_hash, device_id, fcm_token, ip_address, session_info, client_id, scope, expires_at, revoked, created_at, last_used_at FROM user_sessions WHERE device_id = $1 AND revoked = FALSE
`

func (q *Queries) GetSessionByDeviceID(ctx context.Context, deviceID pgtype.UUID) (UserSession, error) {
	row := q.db.QueryRow(ctx, getSessionByDeviceID, deviceID)
	var i UserSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RefreshTokenHash,
		&i.DeviceID,
		&i.FcmToken,
		&i.IpAddress,
		&i.SessionInfo,
		&i.ClientID,
		&i.Scope,
		&i.ExpiresAt,
		&i.Revoked,
		&i.CreatedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const getSessionByID = `-- name: GetSessionByID :one
SELECT id, user_id, refresh_token_hash, device_id, fcm_token, ip_address, session_info, client_id, scope, expires_at, revoked, created_at, last_used_at FROM user_sessions WHERE id = $1
`

func (q *Queries) GetSessionByID(ctx context.Context, id pgtype.UUID) (UserSession, error) {
	row := q.db.QueryRow(ctx, getSessionByID, id)
	var i UserSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RefreshTokenHash,
		&i.DeviceID,
		&i.FcmToken,
		&i.IpAddress,
		&i.SessionInfo,
		&i.ClientID,
		&i.Scope,
		&i.ExpiresAt,
		&i.Revoked,
		&i.CreatedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const getSessionByTokenHash = `-- name: GetSessionByTokenHash :one
SELECT id, user_id, refresh_token_hash, device_id, fcm_token, ip_address, session_info, client_id, scope, expires_at, revoked, created_at, last_used_at FROM user_sessions WHERE refresh_token_hash = $1
`

func (q *Queries) GetSessionByTokenHash(ctx context.Context, refreshTokenHash string) (UserSession, error) {
	row := q.db.QueryRow(ctx, getSessionByTokenHash, refreshTokenHash)
	var i UserSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RefreshTokenHash,
		&i.DeviceID,
		&i.FcmToken,
		&i.IpAddress,
		&i.SessionInfo,
		&i.ClientID,
		&i.Scope,
		&i.ExpiresAt,
		&i.Revoked,
		&i.CreatedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const getSessionByUserAndDevice = `-- name: GetSessionByUserAndDevice :one
SELECT id, user_id, refresh_token_hash, device_id, fcm_token, ip_address, session_info, client_id, scope, expires_at, revoked, created_at, last_used_at FROM user_sessions
WHERE user_id = $1 AND device_id = $2 AND revoked = FALSE
`

type GetSessionByUserAndDeviceParams struct {
	UserID   int64       `json:"user_id"`
	DeviceID pgtype.UUID `json:"device_id"`
}

func (q *Queries) GetSessionByUserAndDevice(ctx context.Context, arg GetSessionByUserAndDeviceParams) (UserSession, error) {
	row := q.db.QueryRow(ctx, getSessionByUserAndDevice, arg.UserID, arg.DeviceID)
	var i UserSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RefreshTokenHash,
		&i.DeviceID,
		&i.FcmToken,
		&i.IpAddress,
		&i.SessionInfo,
		&i.ClientID,
		&i.Scope,
		&i.ExpiresAt,
		&i.Revoked,
		&i.CreatedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const getSessionsByUserID = `-- name: GetSessionsByUserID :many
SELECT id, user_id, refresh_token_hash, device_id, fcm_token, ip_address, session_info, client_id, scope, expires_at, revoked, created_at, last_used_at FROM user_sessions WHERE user_id = $1 ORDER BY last_used_at DESC
`

func (q *Queries) GetSessionsByUserID(ctx context.Context, userID int64) ([]UserSession, error) {
	rows, err := q.db.Query(ctx, getSessionsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserSession
	for rows.Next() {
		var i UserSession
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.RefreshTokenHash,
			&i.DeviceID,
			&i.FcmToken,
			&i.IpAddress,
			&i.SessionInfo,
			&i.ClientID,
			&i.Scope,
			&i.ExpiresAt,
			&i.Revoked,
			&i.CreatedAt,
			&i.LastUsedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeSession = `-- name: RevokeSession :exec
UPDATE user_sessions SET revoked = TRUE WHERE id = $1
`

func (q *Queries) RevokeSession(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, revokeSession, id)
	return err
}

const revokeSessionByDeviceID = `-- name: RevokeSessionByDeviceID :exec
UPDATE user_sessions SET revoked = TRUE WHERE device_id = $1
`

func (q *Queries) RevokeSessionByDeviceID(ctx context.Context, deviceID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, revokeSessionByDeviceID, deviceID)
	return err
}

const revokeSessionsByUserExceptDevice = `-- name: RevokeSessionsByUserExceptDevice :exec
UPDATE user_sessions
SET revoked = TRUE
WHERE user_id = $1 AND device_id != $2
`

type RevokeSessionsByUserExceptDeviceParams struct {
	UserID   int64       `json:"user_id"`
	DeviceID pgtype.UUID `json:"device_id"`
}

func (q *Queries) RevokeSessionsByUserExceptDevice(ctx context.Context, arg RevokeSessionsByUserExceptDeviceParams) error {
	_, err := q.db.Exec(ctx, revokeSessionsByUserExceptDevice, arg.UserID, arg.DeviceID)
	return err
}

const revokeSessionsByUserID = `-- name: RevokeSessionsByUserID :exec
UPDATE user_sessions SET revoked = TRUE WHERE user_id = $1
`

func (q *Queries) RevokeSessionsByUserID(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, revokeSessionsByUserID, userID)
	return err
}

const updateFCMToken = `-- name: UpdateFCMToken :exec
UPDATE user_sessions
SET fcm_token = $2
WHERE refresh_token_hash = $1
`

type UpdateFCMTokenParams struct {
	RefreshTokenHash string      `json:"refresh_token_hash"`
	FcmToken         pgtype.Text `json:"fcm_token"`
}

func (q *Queries) UpdateFCMToken(ctx context.Context, arg UpdateFCMTokenParams) error {
	_, err := q.db.Exec(ctx, updateFCMToken, arg.RefreshTokenHash, arg.FcmToken)
	return err
}

const updateSession = `-- name: UpdateSession :exec
UPDATE user_sessions
SET refresh_token_hash = $2, fcm_token = $3, ip_address = $4,
    session_info = $5, scope = $6, expires_at = $7, last_used_at = $8
WHERE id = $1
`

type UpdateSessionParams struct {
	ID               pgtype.UUID        `json:"id"`
	RefreshTokenHash string             `json:"refresh_token_hash"`
	FcmToken         pgtype.Text        `json:"fcm_token"`
	IpAddress        string             `json:"ip_address"`
	SessionInfo      []byte             `json:"session_info"`
	Scope            string             `json:"scope"`
	ExpiresAt        pgtype.Timestamptz `json:"expires_at"`
	LastUsedAt       pgtype.Timestamptz `json:"last_used_at"`
}

func (q *Queries) UpdateSession(ctx context.Context, arg UpdateSessionParams) error {
	_, err := q.db.Exec(ctx, updateSession,
		arg.ID,
		arg.RefreshTokenHash,
		arg.FcmToken,
		arg.IpAddress,
		arg.SessionInfo,
		arg.Scope,
		arg.ExpiresAt,
		arg.LastUsedAt,
	)
	return err
}

const updateSessionLastUsed = `-- name: UpdateSessionLastUsed :exec
UPDATE user_sessions
SET last_used_at = NOW(), ip_address = $2
WHERE id = $1
`

type UpdateSessionLastUsedParams struct {
	ID        pgtype.UUID `json:"id"`
	IpAddress string      `json:"ip_address"`
}

func (q *Queries) UpdateSessionLastUsed(ctx context.Context, arg UpdateSessionLastUsedParams) error {
	_, err := q.db.Exec(ctx, updateSessionLastUsed, arg.ID, arg.IpAddress)
	return err
}

const updateSessionRefreshToken = `-- name: UpdateSessionRefreshToken :exec
UPDATE user_sessions
SET refresh_token_hash = $2, expires_at = $3, last_used_at = NOW()
WHERE id = $1
`

type UpdateSessionRefreshTokenParams struct {
	ID               pgtype.UUID        `json:"id"`
	RefreshTokenHash string             `json:"refresh_token_hash"`
	ExpiresAt        pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) UpdateSessionRefreshToken(ctx context.Context, arg UpdateSessionRefreshTokenParams) error {
	_, err := q.db.Exec(ctx, updateSessionRefreshToken, arg.ID, arg.RefreshTokenHash, arg.ExpiresAt)
	return err
}
