// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sessions

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CountActiveSessionsByUserID(ctx context.Context, userID int64) (int64, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) error
	DeleteExpiredSessions(ctx context.Context) (int64, error)
	DeleteSession(ctx context.Context, id pgtype.UUID) error
	GetActiveFCMTokensByUserID(ctx context.Context, userID int64) ([]pgtype.Text, error)
	GetActiveSessionsByUserID(ctx context.Context, userID int64) ([]UserSession, error)
	GetOldestActiveSessionByUserID(ctx context.Context, userID int64) (UserSession, error)
	GetSessionByDeviceID(ctx context.Context, deviceID pgtype.UUID) (UserSession, error)
	GetSessionByID(ctx context.Context, id pgtype.UUID) (UserSession, error)
	GetSessionByTokenHash(ctx context.Context, refreshTokenHash string) (UserSession, error)
	GetSessionByUserAndDevice(ctx context.Context, arg GetSessionByUserAndDeviceParams) (UserSession, error)
	GetSessionsByUserID(ctx context.Context, userID int64) ([]UserSession, error)
	RevokeSession(ctx context.Context, id pgtype.UUID) error
	RevokeSessionByDeviceID(ctx context.Context, deviceID pgtype.UUID) error
	RevokeSessionsByUserExceptDevice(ctx context.Context, arg RevokeSessionsByUserExceptDeviceParams) error
	RevokeSessionsByUserID(ctx context.Context, userID int64) error
	UpdateFCMToken(ctx context.Context, arg UpdateFCMTokenParams) error
	UpdateSession(ctx context.Context, arg UpdateSessionParams) error
	UpdateSessionLastUsed(ctx context.Context, arg UpdateSessionLastUsedParams) error
	UpdateSessionRefreshToken(ctx context.Context, arg UpdateSessionRefreshTokenParams) error
}

var _ Querier = (*Queries)(nil)
