version: "2"
sql:
  - engine: "postgresql"
    queries: "queries.sql"
    schema: "../../../../../migrations/000010_create_user_sessions.up.sql"
    gen:
      go:
        package: "sessions"
        out: "."
        sql_package: "pgx/v5"
        emit_json_tags: true
        emit_prepared_queries: false
        emit_interface: true
        emit_exact_table_names: false
