// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package clients

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type OauthClient struct {
	ID               pgtype.UUID        `json:"id"`
	ClientID         string             `json:"client_id"`
	ClientSecretHash pgtype.Text        `json:"client_secret_hash"`
	Name             string             `json:"name"`
	RedirectUris     []string           `json:"redirect_uris"`
	GrantTypes       []string           `json:"grant_types"`
	Scopes           []string           `json:"scopes"`
	IsConfidential   bool               `json:"is_confidential"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}
