// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package clients

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateOAuthClient(ctx context.Context, arg CreateOAuthClientParams) error
	DeleteOAuthClient(ctx context.Context, id pgtype.UUID) error
	GetOAuthClientByClientID(ctx context.Context, clientID string) (OauthClient, error)
	GetOAuthClientByID(ctx context.Context, id pgtype.UUID) (OauthClient, error)
	ListOAuthClients(ctx context.Context, arg ListOAuthClientsParams) ([]OauthClient, error)
	UpdateOAuthClient(ctx context.Context, arg UpdateOAuthClientParams) error
}

var _ Querier = (*Queries)(nil)
