// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: queries.sql

package clients

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOAuthClient = `-- name: CreateOAuthClient :exec
INSERT INTO oauth_clients (id, client_id, client_secret_hash, name, redirect_uris, grant_types, scopes, is_confidential, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
`

type CreateOAuthClientParams struct {
	ID               pgtype.UUID        `json:"id"`
	ClientID         string             `json:"client_id"`
	ClientSecretHash pgtype.Text        `json:"client_secret_hash"`
	Name             string             `json:"name"`
	RedirectUris     []string           `json:"redirect_uris"`
	GrantTypes       []string           `json:"grant_types"`
	Scopes           []string           `json:"scopes"`
	IsConfidential   bool               `json:"is_confidential"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateOAuthClient(ctx context.Context, arg CreateOAuthClientParams) error {
	_, err := q.db.Exec(ctx, createOAuthClient,
		arg.ID,
		arg.ClientID,
		arg.ClientSecretHash,
		arg.Name,
		arg.RedirectUris,
		arg.GrantTypes,
		arg.Scopes,
		arg.IsConfidential,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteOAuthClient = `-- name: DeleteOAuthClient :exec
DELETE FROM oauth_clients WHERE id = $1
`

func (q *Queries) DeleteOAuthClient(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteOAuthClient, id)
	return err
}

const getOAuthClientByClientID = `-- name: GetOAuthClientByClientID :one
SELECT id, client_id, client_secret_hash, name, redirect_uris, grant_types, scopes, is_confidential, created_at, updated_at FROM oauth_clients WHERE client_id = $1
`

func (q *Queries) GetOAuthClientByClientID(ctx context.Context, clientID string) (OauthClient, error) {
	row := q.db.QueryRow(ctx, getOAuthClientByClientID, clientID)
	var i OauthClient
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.ClientSecretHash,
		&i.Name,
		&i.RedirectUris,
		&i.GrantTypes,
		&i.Scopes,
		&i.IsConfidential,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOAuthClientByID = `-- name: GetOAuthClientByID :one
SELECT id, client_id, client_secret_hash, name, redirect_uris, grant_types, scopes, is_confidential, created_at, updated_at FROM oauth_clients WHERE id = $1
`

func (q *Queries) GetOAuthClientByID(ctx context.Context, id pgtype.UUID) (OauthClient, error) {
	row := q.db.QueryRow(ctx, getOAuthClientByID, id)
	var i OauthClient
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.ClientSecretHash,
		&i.Name,
		&i.RedirectUris,
		&i.GrantTypes,
		&i.Scopes,
		&i.IsConfidential,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listOAuthClients = `-- name: ListOAuthClients :many
SELECT id, client_id, client_secret_hash, name, redirect_uris, grant_types, scopes, is_confidential, created_at, updated_at FROM oauth_clients ORDER BY created_at DESC LIMIT $1 OFFSET $2
`

type ListOAuthClientsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListOAuthClients(ctx context.Context, arg ListOAuthClientsParams) ([]OauthClient, error) {
	rows, err := q.db.Query(ctx, listOAuthClients, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OauthClient
	for rows.Next() {
		var i OauthClient
		if err := rows.Scan(
			&i.ID,
			&i.ClientID,
			&i.ClientSecretHash,
			&i.Name,
			&i.RedirectUris,
			&i.GrantTypes,
			&i.Scopes,
			&i.IsConfidential,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOAuthClient = `-- name: UpdateOAuthClient :exec
UPDATE oauth_clients
SET client_secret_hash = $2, name = $3, redirect_uris = $4, grant_types = $5, scopes = $6, is_confidential = $7, updated_at = $8
WHERE id = $1
`

type UpdateOAuthClientParams struct {
	ID               pgtype.UUID        `json:"id"`
	ClientSecretHash pgtype.Text        `json:"client_secret_hash"`
	Name             string             `json:"name"`
	RedirectUris     []string           `json:"redirect_uris"`
	GrantTypes       []string           `json:"grant_types"`
	Scopes           []string           `json:"scopes"`
	IsConfidential   bool               `json:"is_confidential"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateOAuthClient(ctx context.Context, arg UpdateOAuthClientParams) error {
	_, err := q.db.Exec(ctx, updateOAuthClient,
		arg.ID,
		arg.ClientSecretHash,
		arg.Name,
		arg.RedirectUris,
		arg.GrantTypes,
		arg.Scopes,
		arg.IsConfidential,
		arg.UpdatedAt,
	)
	return err
}
