// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package keys

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type SigningKey struct {
	Kid        string             `json:"kid"`
	PrivateKey string             `json:"private_key"`
	PublicKey  string             `json:"public_key"`
	Algorithm  string             `json:"algorithm"`
	Active     bool               `json:"active"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
}
