// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package keys

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	ActivateSigningKey(ctx context.Context, kid string) error
	CreateSigningKey(ctx context.Context, arg CreateSigningKeyParams) error
	DeactivateAllSigningKeys(ctx context.Context) error
	DeleteExpiredSigningKeys(ctx context.Context, expiresAt pgtype.Timestamptz) (int64, error)
	DeleteSigningKey(ctx context.Context, kid string) error
	GetActiveSigningKey(ctx context.Context, expiresAt pgtype.Timestamptz) (SigningKey, error)
	GetAllValidSigningKeys(ctx context.Context, expiresAt pgtype.Timestamptz) ([]SigningKey, error)
	GetSigningKeyByKID(ctx context.Context, kid string) (SigningKey, error)
}

var _ Querier = (*Queries)(nil)
