// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: queries.sql

package keys

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const activateSigningKey = `-- name: ActivateSigningKey :exec
UPDATE signing_keys SET active = TRUE WHERE kid = $1
`

func (q *Queries) ActivateSigningKey(ctx context.Context, kid string) error {
	_, err := q.db.Exec(ctx, activateSigningKey, kid)
	return err
}

const createSigningKey = `-- name: CreateSigningKey :exec
INSERT INTO signing_keys (kid, private_key, public_key, algorithm, active, created_at, expires_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type CreateSigningKeyParams struct {
	Kid        string             `json:"kid"`
	PrivateKey string             `json:"private_key"`
	PublicKey  string             `json:"public_key"`
	Algorithm  string             `json:"algorithm"`
	Active     bool               `json:"active"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateSigningKey(ctx context.Context, arg CreateSigningKeyParams) error {
	_, err := q.db.Exec(ctx, createSigningKey,
		arg.Kid,
		arg.PrivateKey,
		arg.PublicKey,
		arg.Algorithm,
		arg.Active,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	return err
}

const deactivateAllSigningKeys = `-- name: DeactivateAllSigningKeys :exec
UPDATE signing_keys SET active = FALSE
`

func (q *Queries) DeactivateAllSigningKeys(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deactivateAllSigningKeys)
	return err
}

const deleteExpiredSigningKeys = `-- name: DeleteExpiredSigningKeys :execrows
DELETE FROM signing_keys WHERE expires_at < $1
`

func (q *Queries) DeleteExpiredSigningKeys(ctx context.Context, expiresAt pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredSigningKeys, expiresAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteSigningKey = `-- name: DeleteSigningKey :exec
DELETE FROM signing_keys WHERE kid = $1
`

func (q *Queries) DeleteSigningKey(ctx context.Context, kid string) error {
	_, err := q.db.Exec(ctx, deleteSigningKey, kid)
	return err
}

const getActiveSigningKey = `-- name: GetActiveSigningKey :one
SELECT kid, private_key, public_key, algorithm, active, created_at, expires_at FROM signing_keys WHERE active = TRUE AND expires_at > $1 LIMIT 1
`

func (q *Queries) GetActiveSigningKey(ctx context.Context, expiresAt pgtype.Timestamptz) (SigningKey, error) {
	row := q.db.QueryRow(ctx, getActiveSigningKey, expiresAt)
	var i SigningKey
	err := row.Scan(
		&i.Kid,
		&i.PrivateKey,
		&i.PublicKey,
		&i.Algorithm,
		&i.Active,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getAllValidSigningKeys = `-- name: GetAllValidSigningKeys :many
SELECT kid, private_key, public_key, algorithm, active, created_at, expires_at FROM signing_keys WHERE expires_at > $1 ORDER BY created_at DESC
`

func (q *Queries) GetAllValidSigningKeys(ctx context.Context, expiresAt pgtype.Timestamptz) ([]SigningKey, error) {
	rows, err := q.db.Query(ctx, getAllValidSigningKeys, expiresAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SigningKey
	for rows.Next() {
		var i SigningKey
		if err := rows.Scan(
			&i.Kid,
			&i.PrivateKey,
			&i.PublicKey,
			&i.Algorithm,
			&i.Active,
			&i.CreatedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSigningKeyByKID = `-- name: GetSigningKeyByKID :one
SELECT kid, private_key, public_key, algorithm, active, created_at, expires_at FROM signing_keys WHERE kid = $1
`

func (q *Queries) GetSigningKeyByKID(ctx context.Context, kid string) (SigningKey, error) {
	row := q.db.QueryRow(ctx, getSigningKeyByKID, kid)
	var i SigningKey
	err := row.Scan(
		&i.Kid,
		&i.PrivateKey,
		&i.PublicKey,
		&i.Algorithm,
		&i.Active,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}
