// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package users

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	ID          int64              `json:"id"`
	Username    string             `json:"username"`
	SahiyUserID pgtype.Int8        `json:"sahiy_user_id"`
	Phone       string             `json:"phone"`
	Password    []byte             `json:"password"`
	Avatar      pgtype.Text        `json:"avatar"`
	BirthDate   pgtype.Timestamptz `json:"birth_date"`
	Gender      pgtype.Int2        `json:"gender"`
	ForbidLogin pgtype.Int2        `json:"forbid_login"`
	Email       pgtype.Text        `json:"email"`
	ProfileID   pgtype.Int8        `json:"profile_id"`
	RegisterIp  pgtype.Text        `json:"register_ip"`
	LastloginIp pgtype.Text        `json:"lastlogin_ip"`
	Status      int32              `json:"status"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	LastLoginAt pgtype.Timestamptz `json:"last_login_at"`
}
